# Docker Compose file for Chat Room application
# Usage: docker-compose up -d (start), docker-compose down (stop)

services:
  # Web-based chat application (access via browser + ngrok)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: chatroom-web
    ports:
      - "8080:8080"      # Map port 8080 on host to port 8080 in container (HTTP for ngrok)
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - USE_SSL=false    # HTTP mode for ngrok compatibility
